In [1]:
import pandas as pd

path = './online_retail.csv'
df = pd.read_csv(path)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [2]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 33.1 MB

In [6]:
df.dropna(subset=['InvoiceDate'], inplace=True)

df.set_index('InvoiceDate', inplace=True)

In [7]:
df['Year'] = df.index.year
df['Moth'] = df.index.month
df['Day'] = df.index.day
df['Weekday'] = df.index.weekday
df['Hour'] = df.index.hour


df.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Moth,Day,Weekday,Hour
InvoiceDate,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,2010,12,1,2,8

In [ ]:
# df = df.drop(columns=[''])  Para eliminar una columna

In [10]:
df_2011 = df.loc['2011']

df_2011.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Moth,Day,Weekday,Hour
InvoiceDate,,,,,,,,,,,,
2011-01-04 10:00:00,539993,22386,JUMBO BAG PINK POLKADOT,10,1.95,13313.0,United Kingdom,2011,1,4,1,10
2011-01-04 10:00:00,539993,21499,BLUE POLKADOT WRAP,25,0.42,13313.0,United Kingdom,2011,1,4,1,10
2011-01-04 10:00:00,539993,21498,RED RETROSPOT WRAP,25,0.42,13313.0,United Kingdom,2011,1,4,1,10
2011-01-04 10:00:00,539993,22379,RECYCLING BAG RETROSPOT,5,2.10,13313.0,United Kingdom,2011,1,4,1,10
2011-01-04 10:00:00,539993,20718,RED RETROSPOT SHOPPER BAG,10,1.25,13313.0,United Kingdom,2011,1,4,1,10

In [11]:
df_2011_dec = df.loc['2011-12']

df_2011_dec.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Moth,Day,Weekday,Hour
InvoiceDate,,,,,,,,,,,,
2011-12-01 08:12:00,C579889,23245,SET OF 3 REGENCY CAKE TINS,-8,4.15,13853.0,United Kingdom,2011,12,1,3,8
2011-12-01 08:14:00,C579890,84947,ANTIQUE SILVER TEA GLASS ENGRAVED,-1,1.25,15197.0,United Kingdom,2011,12,1,3,8
2011-12-01 08:14:00,C579890,23374,RED SPOT PAPER GIFT BAG,-1,0.82,15197.0,United Kingdom,2011,12,1,3,8
2011-12-01 08:14:00,C579890,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,-2,0.85,15197.0,United Kingdom,2011,12,1,3,8
2011-12-01 08:18:00,C579891,23485,BOTANICAL GARDENS WALL CLOCK,-1,25.00,13644.0,United Kingdom,2011,12,1,3,8

In [12]:
df_dec_range = df.loc['2010-12-01':'20-12-15']
df_dec_range.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Moth,Day,Weekday,Hour
InvoiceDate,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,2010,12,1,2,8

La frecuencia en 'D' significa "Day"

In [15]:
date_range_new = pd.date_range(start='2024-01-01', end='2024-12-31', freq='D')
df_dates = pd.DataFrame(date_range_new, columns=['Date'])
df_dates.head(10)

        Date
0 2024-01-01
1 2024-01-02
2 2024-01-03
3 2024-01-04
4 2024-01-05
5 2024-01-06
6 2024-01-07
7 2024-01-08
8 2024-01-09
9 2024-01-10